image: python:3.8

stages:
  - test

before_script:
  - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
  - export PATH=$PATH:$HOME/.poetry/bin
  - poetry install

cache:
  paths:
    - pip-cache

test_post_train:
  stage: test
  script: poetry run pytest
  only:
    - merge_requests
