image: python:3.7

stages:
  - test

before_script:
  - export PIP_CACHE="pip-cache"
  - pip install pandas
  - pip install pytest

cache:
  paths:
    - pip-cache

test_post_train:
  stage: test
  script: pytest src/test_build_features.py
  only:
    - merge_requests
