image: python:3.8

stages:
  - test

before_script:
  - pip install poetry
  - poetry install
  - pip install pytest

cache:
  paths:
    - pip-cache

test_post_train:
  stage: test
  script: poetry run pytest
  only:
    - merge_requests
