image: python:3.7

stages:
  - test
  - deploy

before_script:
  - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
  - export PATH=$PATH:$HOME/.poetry/bin
  # - source $HOME/.poetry/bin
  - poetry install

full_test:
  stage: test
  script: poetry run pytest
  only:
    - pushes


# metrics:
#   stage: test
#   only:
#     refs:
#       - preprod
#       - merge_requests
#     changes:
#       - models/*.pkl
#   script: |+
#     ls metrics.txt && rm metrics.txt  # override current metrics.txt for proper diffing
#     for filename in $(ls models/*.pkl); do
#       python src/score_producer.py "$filename" data/test.csv accuracy_score >> metrics.txt
#     done
#     cat metrics.txt
#   artifacts:
#     reports:
#       metrics: metrics.txt
