subscription:
  name: 'data.csv'
  date_format: '%Y-%m-%d'
  sep: ';'
  cast_types:
    'DATE': datetime64

economic_info:
  name: 'socio_eco.csv'
  date_format: '%Y-%m-%d'
  sep: ';'
  cast_types:
    'DATE': datetime64


